# Используем официальный образ Node.js версии 20.14
FROM node:20.14

# Устанавливаем рабочую директорию
WORKDIR /app

COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем файлы проекта
COPY ../dist/apps/back-app .

# Открываем порт для Node.js
EXPOSE 3000

# Команда для запуска приложения
CMD ["node", "main.js"]

